version: 2
jobs:
  build:
    docker:
      # CircleCI Go images available at: https://hub.docker.com/r/circleci/golang/
      - image: circleci/golang:1.10.1
    working_directory: ~/ndid/test
    steps:
      - checkout
      - run:
          name: Install Node.js
          command: curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash - && sudo apt-get install -y nodejs
      - run:
          name: Install Tendermint ABCI
          command: go get github.com/tendermint/abci/cmd/abci-cli
      - run:
          name: Install Tendermint
          command: |
            wget https://github.com/tendermint/tendermint/releases/download/v0.19.0/tendermint_0.19.0_linux_amd64.zip
            unzip tendermint_0.19.0_linux_amd64.zip
            sudo install tendermint /usr/local/bin
      - run:
          name: Install project dependencies (todo use a dep management solution?)
          command: |
            go get github.com/fatih/color
      - run:
          name: Create logs directory
          command: |
            mkdir -p ~/logs
      - run: git clone https://github.com/ndidplatform/smart-contract.git /go/src/github.com/ndidplatform/smart-contract
      - run: git clone https://github.com/ndidplatform/api.git ~/ndid/api
      - run:
          name: idp-abci
          command: |
            (
              CALLBACK_URI=http://localhost:3000/callback go run abci/server.go tcp://127.0.0.1:46000
            ) >> ~/logs/idp-abci.log 2>&1
          background: true
      - run:
          name: idp-tendermint
          command: |
            (
              tendermint --home ./config/tendermint/IdP unsafe_reset_all && \
              tendermint --home ./config/tendermint/IdP node --consensus.create_empty_blocks=false
            ) >> ~/logs/idp-tendermint.log 2>&1
          background: true
      - run:
          name: rp-abci
          command: |
            (
              CALLBACK_URI=http://localhost:3001/callback go run abci/server.go tcp://127.0.0.1:46001
            ) >> ~/logs/rp-abci.log 2>&1
          background: true
      - run:
          name: rp-tendermint
          command: |
            (
              tendermint --home ./config/tendermint/RP unsafe_reset_all && \
              tendermint --home ./config/tendermint/RP node --consensus.create_empty_blocks=false
            ) >> ~/logs/rp-tendermint.log 2>&1
          background: true
      - run: sleep 20
      - store_artifacts:
          path: ~/logs
          destination: logs
